### ISSUE TITLE
keys left behind in code

### ISSUE THREAD

**Issue by tanmaykm** [dls/DynamoDB.jl#1]
You probably didn't intend to leave the keys behind here:
https://github.com/dls/DynamoDB.jl/blob/0a00b00f578aa7965182ed4d9d3248308831f41a/test/integration_tests.jl#L11

Unless they are not for a real server.

**Comment by dls** [comment]
Hi Tanmaykm,

Those keys only have IAM permission for operations on my JULIA_TESTING table -- the only potential security risk is someone could cause a spurious test failure by deleting or editing a row during a test run... and use of UUIDs in the test makes sure that could only happen maliciously :p. If that does happen I'll work out something more complicated out, but for now it seems nice having a way for anyone to do a full integration test w/o any set up requirements.

(Incidentally, this kind of  "two layer webapp" model is one of the things I love about DynamoDB.jl. At the bottom of the file you link there is an example IAM permission, and some links if you'd like to learn more)

Thanks for taking the time to point this out. I'll make the "not a bug" notice above that line a bit more direct. Thanks!

**Comment by Keno** [comment]
Note that Amazon will revoke IAM keys they find on GitHub, so this might not work out the way you expect.

**Comment by dls** [comment]
That would be really surprising to me -- kind of excited to see if they do it. Their documentation talks proudly about you can use DynamoDB w/o a server (for a mobile app or a github page) using [row-level IAM policies](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/FGAC_DDB.html).

I could understand revoking IAMs for EC2 and S3 though -- those APIs are pay-per-use.

**Comment by dls** [comment]
Well, hmm, _some_ S3 IAMs -- like, if it's a read-only IAM on an S3 bucket, that seems like something you should be allowed to distribute (though still cleaner to just make the item public). Anyway, I'll keep an eye on my email. Thanks for the heads up.

**Comment by dls** [comment]
@Keno for both our references, Amazon did email me about this (automated, from a scan). Once they understood what I was doing they said it was fine and closed the case.
